[package]
name = "nine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
raylib = "5.0.2"
rust-embed = { version = "8.5.0", features = ["debug-embed"] }
